### ISSUE TITLE
backport commits for keyboard on plustoo?

### ISSUE THREAD

**Issue by jsmolina** [MiSTer-devel/MacPlus_MiSTer#13]
there are some keyboard fixes there
https://github.com/mist-devel/plus_too/pull/5

**Comment by sorgelig** [comment]
try this build:
[MacPlus_t1.zip](https://github.com/user-attachments/files/16990783/MacPlus_t1.zip)

**Comment by jsmolina** [comment]
> try this build: [MacPlus_t1.zip](https://github.com/user-attachments/files/16990783/MacPlus_t1.zip)

No regression so far with this build. Everything works as expected.

I tried using cursors on MacWrite, and it works on both versions (old and new)

**Comment by sorgelig** [comment]
I'm not familiar with MacPlus hardware. Probably it's just 2 versions of keyboard, as i see it sends different IDs. So probably this change mostly useless. Unless there is some specific application requiring new type of keyboard.

**Comment by jsmolina** [comment]
Oh I see they documented on here 
https://github.com/mist-devel/plus_too/issues/4


copying here:

it turns out that 0x71 is just the keycode for Shift. Sending 0x71 before the troublesome keycodes does indeed fix them, but the shift keypress needs releasing afterwards.

But since the 0x10b scancode that used to be on cursor-up accidentally triggered a "+" keypress without the extra prefix, I'm wondering if the 0x71 prefix is correct, or just a side effect of how the key decoding is done - and maybe there are correct scancodes for those keys that need to be discovered?

Edit: OK it makes more sense now:
The original M0110 keyboard could be used with an optional M0120 keypad, which had four cursor keys around the numpad. Those keys emitted calc functions (+ * / .) if the shift key was pressed.
The M0110A integrated the numpad and added dedicated cursor keys. The numpad calc keys now don't need shifting to access them, but those four keys still emit a shift code when pressed.

https://deskthority.net/wiki/Apple_M0120
Some good information here:
https://github.com/tmk/tmk_keyboard/wiki/Apple-M0110-Keyboard-Protocol

**Comment by jsmolina** [comment]
it's done now, lot of thanks
