### ISSUE TITLE
Keyboard has issues

### ISSUE THREAD

**Issue by BigErn77** [MiSTer-devel/MacPlus_MiSTer#3]
Sometimes when typing, entering a single character causes it to be entered multiple times. Sometimes when this happens the key pressed keeps getting input with no way to stop it. Other times the capslock gets "stuck" either on or off. The keyboard is basically totally messed up, it's not just a single problem.

**Comment by jsmolina** [comment]
I've reproduced exactly the same. For games it gets really annoying. Imagine prince of persia forced running to skewers...

Also, I have a physical mac and it does have joystick support. This core has it?

Regards.

**Comment by Juananlaguna** [comment]
I´m having the same issue. The keyboard is not responding accurately. :(

I wonder a fix for this core. I would appreciate it.

Thank you for your attention. :)

**Comment by reversecyborg** [comment]
I'm getting the same issue on the latest core, the keyboard behaves very strangely, exact same issue as reported on August 14th 2019. I also experience mouse issues, like the inability to double click. Instead the mouse either just selects or deselects the icon. The core also doesn't seem to read disks that it should, and sometimes freezes trying to read disks that normally do work.

**Comment by andiweli** [comment]
Same issue still in 2021.

**Comment by BigErn77** [comment]
Issue appears to be fixed.
